# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protofile import user_pb2 as protofile_dot_user__pb2


class UserStub(object):
    """what client can do or what server can provide
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/User/Login',
                request_serializer=protofile_dot_user__pb2.UserRequest.SerializeToString,
                response_deserializer=protofile_dot_user__pb2.UserResponse.FromString,
                )
        self.Ping = channel.unary_unary(
                '/User/Ping',
                request_serializer=protofile_dot_user__pb2.UserRequest.SerializeToString,
                response_deserializer=protofile_dot_user__pb2.UserResponse.FromString,
                )


class UserServicer(object):
    """what client can do or what server can provide
    """

    def Login(self, request, context):
        """
        from_client = {user=string, password=string}
        from_server = {data=map}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """
        from_client = {auth=string, password=string}
        from_server = {data=map}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=protofile_dot_user__pb2.UserRequest.FromString,
                    response_serializer=protofile_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=protofile_dot_user__pb2.UserRequest.FromString,
                    response_serializer=protofile_dot_user__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """what client can do or what server can provide
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/User/Login',
            protofile_dot_user__pb2.UserRequest.SerializeToString,
            protofile_dot_user__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/User/Ping',
            protofile_dot_user__pb2.UserRequest.SerializeToString,
            protofile_dot_user__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
