# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protofile/user.proto\"I\n\x0bUserRequest\x12\x11\n\x04\x61uth\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x07payload\x18\x02 \x01(\x0b\x32\r.UserPayloadsB\x07\n\x05_auth\"Y\n\x0cUserPayloads\x12\x1f\n\x05login\x18\x01 \x01(\x0b\x32\x0e.LoginPayloadsH\x00\x12\x1d\n\x04ping\x18\x02 \x01(\x0b\x32\r.PingPayloadsH\x00\x42\t\n\x07payload\"*\n\rLoginPayloads\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\"\x1c\n\x0cPingPayloads\x12\x0c\n\x04text\x18\x01 \x01(\t\"*\n\x0cUserResponse\x12\x1a\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0c.UserResults\"j\n\x0bUserResults\x12\x1f\n\x05login\x18\x01 \x01(\x0b\x32\x0e.LoginResponseH\x00\x12\x1d\n\x04ping\x18\x02 \x01(\x0b\x32\r.PingResponseH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x42\n\n\x08response\"+\n\rLoginResponse\x12\r\n\x05token\x18\x02 \x01(\tR\x0btoken_value\"\x1c\n\x0cPingResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2U\n\x04User\x12&\n\x05Login\x12\x0c.UserRequest\x1a\r.UserResponse\"\x00\x12%\n\x04Ping\x12\x0c.UserRequest\x1a\r.UserResponse\"\x00\x62\x06proto3')



_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
_USERPAYLOADS = DESCRIPTOR.message_types_by_name['UserPayloads']
_LOGINPAYLOADS = DESCRIPTOR.message_types_by_name['LoginPayloads']
_PINGPAYLOADS = DESCRIPTOR.message_types_by_name['PingPayloads']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
_USERRESULTS = DESCRIPTOR.message_types_by_name['UserResults']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_PINGRESPONSE = DESCRIPTOR.message_types_by_name['PingResponse']
UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserPayloads = _reflection.GeneratedProtocolMessageType('UserPayloads', (_message.Message,), {
  'DESCRIPTOR' : _USERPAYLOADS,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:UserPayloads)
  })
_sym_db.RegisterMessage(UserPayloads)

LoginPayloads = _reflection.GeneratedProtocolMessageType('LoginPayloads', (_message.Message,), {
  'DESCRIPTOR' : _LOGINPAYLOADS,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:LoginPayloads)
  })
_sym_db.RegisterMessage(LoginPayloads)

PingPayloads = _reflection.GeneratedProtocolMessageType('PingPayloads', (_message.Message,), {
  'DESCRIPTOR' : _PINGPAYLOADS,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:PingPayloads)
  })
_sym_db.RegisterMessage(PingPayloads)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

UserResults = _reflection.GeneratedProtocolMessageType('UserResults', (_message.Message,), {
  'DESCRIPTOR' : _USERRESULTS,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:UserResults)
  })
_sym_db.RegisterMessage(UserResults)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'protofile.user_pb2'
  # @@protoc_insertion_point(class_scope:PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=24
  _USERREQUEST._serialized_end=97
  _USERPAYLOADS._serialized_start=99
  _USERPAYLOADS._serialized_end=188
  _LOGINPAYLOADS._serialized_start=190
  _LOGINPAYLOADS._serialized_end=232
  _PINGPAYLOADS._serialized_start=234
  _PINGPAYLOADS._serialized_end=262
  _USERRESPONSE._serialized_start=264
  _USERRESPONSE._serialized_end=306
  _USERRESULTS._serialized_start=308
  _USERRESULTS._serialized_end=414
  _LOGINRESPONSE._serialized_start=416
  _LOGINRESPONSE._serialized_end=459
  _PINGRESPONSE._serialized_start=461
  _PINGRESPONSE._serialized_end=489
  _USER._serialized_start=491
  _USER._serialized_end=576
# @@protoc_insertion_point(module_scope)
